version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: tooling
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash ./bash/dev_environment.bash
    volumes:
      - .:/tooling:cached
      - /tooling/tmp
      - /tooling/log
      - /tooling/vender
    ports:
      - "80:3000"
      - "3035:3035"
    depends_on:
      - db
