version: "3"
services:
  db:
    image: mysql:5.7
    env_file: ./docker.env
    ports:
      - "3306:3306"

  web:
    build: .
    command: bash ./bash/environment.bash
    environment:
      RAILS_ENV: production
    volumes:
      - .:/tooling:cached
      - /tooling/tmp
      - /tooling/log
      - /tooling/vender
    ports:
      - "80:3000"
      - "3035:3035"
    depends_on:
      - db
